Filter other bot when starts with At
mamoe/mirai-console pull request #132
Opened 2020-08-26 16:17 UTC by Karlatemp

2020-08-26 16:48 UTC, Him188 commented
感谢你的帮助，但使用 
```
val at = message.asSequence().filterIsInstance<MessageContent>().firstOrNull()
```
替代会更好，逻辑更清晰

2020-08-27 01:08 UTC, Him188 requested changes

2020-08-27 01:08 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/command/CommandManagerImpl.kt
> +                    .filter { it !is PlainText || it.content.trim().isNotEmpty() }
`.trim().isNotEmpty()` 可替换为 `isNotBlank()`

2020-08-27 01:08 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/command/CommandManagerImpl.kt
> +                    // Remove ( [N of Empty PlainText(worst)] [At] )
可使用 `sequence.dropWhile { it.content.isBlank() }` 去除开头的空白 `PlainText`

2020-08-27 01:08 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/command/CommandManagerImpl.kt
> +                    looping@ for (i in result.indices) {
同上, 使用 sequence.dropWile 效果相同

2020-08-27 03:41 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/command/CommandManagerImpl.kt
> +                    // Remove ( [N of Empty PlainText(worst)] [At] )
使用 dropWhile 会把MessageSource一同drop掉

2020-08-27 03:42 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/command/CommandManagerImpl.kt
> +                    looping@ for (i in result.indices) {
这里并不能用dropWhie, 而是应该用 mapFirst, 目前还没有实现

2020-09-21 02:29 UTC, Him188 commented
新指令会以另外的方式解析receiver

2020-09-21 02:29 UTC, closed without merging