Plugin dependencies loading.
mamoe/mirai-console pull request #155
Opened 2020-09-04 12:32 UTC by Karlatemp

close #152

2020-09-13 03:31 UTC, Him188 requested changes
见评论。

还需要在 Plugins.md 添加有关 ExportManager 的文档

2020-09-13 03:31 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> +    public fun isExported(className: String): Boolean
classQualifiedName

2020-09-13 03:31 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> +public fun interface ExportManager {
添加文档

2020-09-13 03:31 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> +    public object AllExported : ExportManager {
添加文档

2020-09-13 03:31 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> +public fun interface ExportManager {
此时不应该是 `fun interface.`

2020-09-13 03:31 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/JarPluginLoaderImpl.kt
> +                val exportManagers = pluginClassLoader.findServices(
这段插入的代码应该使用 Sequence.onEach，不影响 map

2020-09-13 03:31 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/ExportManagerImpl.kt
> +        fun parse(lines: Iterator<String>): ExportManagerImpl {
添加文档说明解析规则
或添加示例

2020-09-13 03:32 UTC, Him188 commented
另外这是否有必要？ J9 模块化的 module-info 可以做这样的工作吗

2020-09-13 03:34 UTC, Karlatemp commented
> 另外这是否有必要？ J9 模块化的 module-info 可以做这样的工作吗

Java 9+的模块化一般情况只能用于SystemClassLoader, 对于插件这种动态加载的来说很难实现, 并且使用module-info的话，可能会引起其他加载错误(亲身经历)

2020-09-13 03:47 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> +    public fun isExported(className: String): Boolean
这是从Java的ClassLoader中继承来的风格，Java的ClassLoader中都是name或者className

2020-09-13 03:48 UTC, Him188 requested changes

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/JarPluginLoaderImpl.kt
> +    internal val classLoaders: ConcurrentLinkedQueue<JvmPluginClassLoader> = ConcurrentLinkedQueue()
不需要 concurrent，插件加载是顺序的

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/JvmPluginClassLoader.kt
> +            throw it
仅在 lambda 很小（单行，短）时使用 it。其他时候都显式指定参数名称

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/JvmPluginClassLoader.kt
> +    internal fun findClass(name: String, disableGlobal: Boolean): Class<*>? {
添加流程注释，或将这个大函数分成几个小函数以帮助阅读者

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/JvmPluginClassLoader.kt
> +                    }.getOrElse { err ->
`.onFailure` 随后 `.getOrNull` 使逻辑更清晰

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/ExportManagerImpl.kt
> +                        if (argument.isBlank()) {
替换为 when

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/ExportManagerImpl.kt
> +                    val splitter = trimed.indexOf(' ')
使用 `substringBefore`, `substringAfter` 而不要处理 index。即使它们会重复几次搜索，但这对性能影响微乎其微

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/ExportManagerImpl.kt
> +                kotlin.run {
多余的 `kotlin.run`

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/ExportManagerImpl.kt
> +                        if (argument.isBlank()) {
替换为 when

2020-09-13 03:48 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/ExportManagerImpl.kt
> +                if (trimed[0] == '#') return@forEach
后面所有代码都没有用到 `line`，而用的是 `trimed`。
因此可以在 `forEach` 前把 `line filter` 和 `map` 之后再使用

2020-09-13 03:49 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> +    public fun isExported(className: String): Boolean
那么添加相关 KDoc 解释可能的误解

2020-09-16 10:13 UTC, Him188 requested changes

2020-09-16 10:13 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> + * export org.example.miraiconsole.myplugin.api.
我认为这个规则并没必要. 像 Java 9 那样 exports 整个 package 已经可以满足需求
或者可以定义默认导出 package, 可选通过其他语法到处单个类

2020-09-16 10:13 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> + * # export 运行插件访问一个类, 或者一个包
此语境下应该使用 `exports`  (修改所有 `export` 为 `exports`)

2020-09-16 10:13 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> + * deny org.example.miraiconsole.myplugin.internal.
`deny` 不适合这样的语境, 需要更换.

2020-09-16 10:13 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/plugin/jvm/ExportManager.kt
> + * 我们允许插件将一些内部实现hidden起来， 避免其他插件调用， 要启动这个特性，
较口语化.

应减少使用 "我们", "你", "起来" 等词语. 
可使用祈使句, 或使用 "请" 字开始一句话替代 "你", "我们" 这样的主语. 

尽量使文字精炼, 如 "只需要在你的 resources 文件夹创建名为 `export-rules.txt` 的规则文件，便可以控制插件的类的公开规则" 可修改为 "如要控制插件类的公开规则，请在 resources 目录创建 `export-rules.txt` 文件"

2020-09-17 12:51 UTC, Him188 commented
在解决后重新 request review

2020-10-24 09:57 UTC, Him188 requested changes
1. 语义上应该叫 `exports`  而不是 `export`。
此处主语应该是 'the plugin' 或 'this rule'，故动词使用 `exports`。

2. 是否可以合并这两个规则（导出包或者类）？即如果 `exports` 的右侧指向一个类就导出这个类，否则导出这个包 (因为极少情况会出现 class 名称与一个包名相同的情况)。

3. 如何处理 Kotlin 的 toplevel class？一个文件内的 toplevel 函数都会被编译为 XxxKt.class，如何通过 `exports` 规则表示这种 class？

2020-10-27 10:23 UTC, Him188 approved these changes

2020-10-27 10:24 UTC, Him188 requested changes

2020-10-27 10:24 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/plugin/ExportManagerImpl.kt
> + * Copyright (c) 2018-2020 Karlatemp. All rights reserved.
Copyright 2019-2020 Mamoe Technologies and contributors.

2020-10-27 11:42 UTC, merged