PermissionService & Permissions
mamoe/mirai-console pull request #156
Opened 2020-09-07 14:03 UTC by Him188

Closes #140

2020-09-07 15:48 UTC, Karlatemp requested changes

2020-09-07 15:48 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/permission/Permissible.kt
> +    public object Console : AbstractPermissibleIdentifier()
`public class` 改成 `plugin data class` 以便直接用于Cache系统的主键

2020-09-07 15:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/permission/Permissible.kt
> +    public object Console : AbstractPermissibleIdentifier()
属于一个遗漏

2020-09-07 15:53 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/permission/Permissible.kt
> +    public object Console : AbstractPermissibleIdentifier()
但这可能导致与相邻 object 的行为不符。

可能只会实现 equals 和 compareTo

2020-09-07 16:13 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/permission/Permissible.kt
> +    public object Console : AbstractPermissibleIdentifier()
object本身就已经可以当主键使用，需要的是让临近的class成为data，或者自行实现hashcode和equals，便于直接作用于各种缓存系统

2020-09-08 04:52 UTC, Karlatemp requested changes

2020-09-08 04:52 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/command/CommandSender.kt
> +
`user.id` 和 `group.id` 反了

2020-09-08 04:52 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/command/CommandSender.kt
> +
根据上下文得知应该再加一个 `groupId`

2020-09-08 05:02 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/command/CommandSender.kt
> +
((好像忘记选comment类型了，这都是request change

2020-09-08 05:33 UTC, mzdluo123 approved these changes

2020-09-08 12:16 UTC, merged