Sem Version
mamoe/mirai-console pull request #164
Opened 2020-09-12 17:12 UTC by Karlatemp

2020-09-12 17:41 UTC, Him188 requested changes

2020-09-12 17:41 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +    public fun toStructureString(): String {
`toStructuredString`

2020-09-12 17:41 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +    public fun interface RangeChecker {
">=1.0.0" 表示的是一种要求

让 `RangeChecker` 叫做 `RangeRequirement`，并设计 `SemVerison.satisfies(RangeRequirement)` 可能更好？

2020-09-12 17:41 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +    public val mainVersion: IntArray,
无特殊需求，无需使用 `@JvmField`

2020-09-12 17:54 UTC, Tamce commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +        val chunks0 = identifier0.split('-')
根据semver2.0：https://semver.org/lang/zh-CN/
identifier是可以允许.出现得，因此应该按照 `-` **或者** `.` 进行 split？

2020-09-16 09:51 UTC, Him188 requested changes

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +    public operator fun compareTo(version: SemVersion): Int {
` SemVersion : Comparable<SemVersion>` ?

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +    override fun equals(other: Any?): Boolean {
> <p>It is strongly recommended, but <i>not</i> strictly required that {@code (x.compareTo(y)==0) == (x.equals(y))}.  Generally speaking, any class that implements the {@code Comparable} interface and violates this condition should clearly indicate this fact.  The recommended language is "Note: this class has a natural ordering that is inconsistent with equals."

来自 JDK `Comparable.compareTo`

因此请添加 KDoc

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +public data class SemVersion(
添加必要的文档

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +public fun SemVersion.satisfies(requirement: SemVersion.RangeRequirement): Boolean = requirement.check(this)
考虑放入 `companion object` 并 `@JvmStatic` 以提供更好的 Java API. (或以其他方式)

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +        public fun parse(version: String): SemVersion {
public 的 API 需要有文档

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +        public fun parseRangeRequirement(requirement: String): RangeRequirement {
public 的 API 需要有文档

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +    public fun toStructuredString(): String {
public 的 API 需要有文档

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +public fun SemVersion.RangeRequirement.check(version: String): Boolean = check(SemVersion.parse(version))
考虑放入 `companion object` 并 `@JvmStatic` 以提供更好的 Java API. (或以其他方式)

2020-09-16 09:51 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +        public fun parse(version: String): SemVersion {
考虑将这些过长的方法实现放入 `SemVersionInternal` 以提供更好的源码阅读体验?

2020-09-16 15:42 UTC, Him188 requested changes

2020-09-16 15:42 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +         * 检查是否满足 [requirement]
使用 “当满足 [requirement] 时返回 `true` ”这样的表述更好

2020-09-16 15:42 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +         * 对于多个规则, 也允许使用 `||` 拼接在一起 E.g:
“例如”

2020-09-16 16:08 UTC, Him188 requested changes

2020-09-16 16:08 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/SemVersion.kt
> +        /** 检查给定版本号[version] 是否满足此依赖要求 */
```
在 [version] 满足此要求时返回 \`true\`
```

2020-09-16 22:54 UTC, Him188 approved these changes

2020-09-17 12:52 UTC, merged