Terminal
mamoe/mirai-console pull request #179
Opened 2020-09-14 05:33 UTC by Karlatemp

2020-09-14 08:20 UTC, Him188 requested changes

2020-09-14 08:20 UTC, Him188 commented on frontend/mirai-console-terminal/src/main/kotlin/net/mamoe/mirai/console/pure/MiraiConsolePureLoader.kt
> +    level = DeprecationLevel.HIDDEN,
ERROR

2020-09-16 09:37 UTC, Him188 requested changes

2020-09-16 09:37 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/MiraiConsole.kt
> +        public suspend fun shutdown() {
删除. 要关闭 MiraiConsole, 只需停止 MiraiConsole 的 job

2020-09-16 09:37 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/MiraiConsole.kt
> +        public val isShutDowning: Boolean
应该显式使用 job.isActive

2020-09-16 09:37 UTC, Him188 commented on frontend/mirai-console-terminal/src/main/kotlin/net/mamoe/mirai/console/pure/MiraiConsolePureLoader.kt
> +    message = "for binary compatibility",
提示使用者更改调用

2020-09-16 09:37 UTC, Him188 commented on frontend/mirai-console-terminal/src/main/kotlin/net/mamoe/mirai/console/terminal/MiraiConsoleImplementationTerminal.kt
> +                    val pumpField = AbstractWindowsTerminal::class.java.getDeclaredField("pump").also {
有潜在不兼容问题, 应该避免使用这样的方法

2020-09-16 09:37 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/MiraiConsole.kt
> +        public suspend fun shutdown() {
(至少不应该轻易添加这个 API)

2020-09-16 10:08 UTC, Karlatemp commented on frontend/mirai-console-terminal/src/main/kotlin/net/mamoe/mirai/console/terminal/MiraiConsoleImplementationTerminal.kt
> +                    val pumpField = AbstractWindowsTerminal::class.java.getDeclaredField("pump").also {
为了检测windows下输入是否可用只能这样

2020-09-16 10:15 UTC, Him188 commented on frontend/mirai-console-terminal/src/main/kotlin/net/mamoe/mirai/console/terminal/MiraiConsoleImplementationTerminal.kt
> +                    val pumpField = AbstractWindowsTerminal::class.java.getDeclaredField("pump").also {
那就写个 try-catch 处理吧

2020-09-17 12:52 UTC, Him188 commented
在解决后重新 request review

2020-09-17 16:25 UTC, Him188 requested changes

2020-09-17 16:25 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/CoroutineScopeUtils.kt
> +) : kotlinx.coroutines.JobImpl(parent) {
实现 `JobImpl` 非常危险.

2020-09-17 16:25 UTC, Him188 commented on frontend/mirai-console-terminal/src/main/kotlin/net/mamoe/mirai/console/pure/MiraiConsolePureLoader.kt
> +    message = "Please uer MiraiConsoleTerminalLoader",
'use'

2020-09-17 16:25 UTC, Him188 commented on settings.gradle.kts
> +includeProject(":mirai-console-gradle", "gradle-plugin")
Merge with origin/master

2020-09-18 00:36 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/util/CoroutineScopeUtils.kt
> +) : kotlinx.coroutines.JobImpl(parent) {
这是debug时的代码，commit忘记忽略了

2020-09-18 04:10 UTC, Him188 approved these changes

2020-09-18 04:43 UTC, merged