重构 command 系统
mamoe/mirai-console pull request #190
Opened 2020-09-19 08:09 UTC by Karlatemp

- [x] 支持解析 optional argument
- [ ] 支持 存在 `sub list` 与 `sub` 的优先 reslove
- [ ] `CommandExecuteResult` 添加介于 `Success` 与 `Failed` 之间的 `IllegalArgument`
- [ ] 在确定主命令的时候仅拆分第一个识别符, 剩下的部分原封不动传给 command, 由 command 进行二次解析

2020-09-19 17:51 UTC, Him188 commented
提案：

## 指令解析阶段

### 1. Lexical Phase

词法分析阶段，分析 `MessageChain`，产生 argument 可能的类型集合的有序参数列表。如 `[String, String|Int，String|Image]`，其中 `|` 表示 or。

允许插件提供扩展。Console 内建简单空格分隔的实现。

### 2. Matching Phase

- Command 提供 descriptor，声明其名称和期望的第一个，第二个或更多参数（如果有具体类型）的可能性。如一个指令可声明 `{名称} {String|Int} {String|Image}`
- CommandManager 寻找最佳参数匹配。若结果不是 100% 唯一，认定无匹配。
- 生参数被传给 Command

### 3. Parsing Phase

- RawCommand 无语境解析，直接处理生参数
- AbstractReflectionCommand 在此阶段解析生参数到指令需要的类型


*详细解析过程待更新*

2020-09-20 13:44 UTC, Him188 commented
`CommandExecuteResult.IllegalArgument` 不错, 可以直接合并

但此 PR 另一部分的 Command 参数处理不可以, 根据 #192, Command 会被完全重构

2020-09-20 13:45 UTC, Him188 requested changes
`CommandExecuteResult.IllegalArgument` 不错, 可以直接合并

但此 PR 另一部分的 Command 参数处理不可以, 根据 #192, Command 会被完全重构

考虑退回到只添加 `IllegalArgument` 的状态?

2020-09-20 13:47 UTC, Karlatemp commented
此pr是完整重构command系统的分支，专门重写command的，彻底重写完毕后再进行review和merge



---原始邮件---
发件人: "Him188"<notifications@github.com&gt;
发送时间: 2020年9月20日(周日) 晚上9:46
收件人: "mamoe/mirai-console"<mirai-console@noreply.github.com&gt;;
抄送: "Karlatemp"<karlatemp@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [mamoe/mirai-console] 重构 command 系统 (#190)




 
@Him188 requested changes on this pull request.
 
CommandExecuteResult.IllegalArgument 不错, 可以直接合并
 
但此 PR 另一部分的 Command 参数处理不可以, 根据 #192, Command 会被完全重构
 
考虑退回到只添加 IllegalArgument 的状态?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-08 03:48 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/command/parse/CommandValueArgument.kt
> +}
作为解析出来的参数, `value` 使用 `String` 会缺失大部分数据(对于非纯文本命令), 考虑换成 `Message` 或者 `Any`

2020-10-08 04:14 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/command/parse/CommandValueArgument.kt
> +}
将会以 `MessageContent` 替换

2020-10-08 07:01 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/command/parse/CommandValueArgument.kt
> +}
可以使用 `SingleMessage` 替换以允许 `MessageMetadata` 的获取

2020-10-08 08:08 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/command/parse/CommandValueArgument.kt
> +}
metadata 不属于 ValueArgument？但也没有一个很好的方式表示

2020-10-09 02:20 UTC, Him188 commented
经过考虑, 认为 `MessageMetadata` 不属于 `CommandValueArgument`.

将来可能会引入一种 `CommandContextArgument` (类似于泛型). 或者让 `CommandCallResolver` 将 `MessageMetadata`  '转换'为 `CommandValueArgument`

2020-10-24 13:23 UTC, Him188 approved these changes

2020-10-24 13:23 UTC, merged