Logger Controller
mamoe/mirai-console pull request #212
Opened 2020-10-24 12:10 UTC by Karlatemp

2020-10-25 12:21 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/MiraiDelegateLogger.kt
> +package net.mamoe.mirai.console.logging
internal class 放在 internal package

2020-10-25 12:21 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/MiraiConsoleLoggerUnused.kt
> +package net.mamoe.mirai.console.logging
internal class 放在 internal package

2020-10-25 12:29 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/MiraiConsoleLoggerControllerPlatformBase.kt
> +public abstract class MiraiConsoleLoggerControllerPlatformBase : MiraiConsoleLoggerController {
名称过长，考虑改名 `AbstractLoggerController`?

2020-10-25 12:29 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/MiraiConsoleLoggerControllerForFrontend.kt
> +public abstract class MiraiConsoleLoggerControllerForFrontend : MiraiConsoleLoggerControllerPlatformBase() {
名称过长

2020-10-25 12:29 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/MiraiConsoleLoggerController.kt
> +public interface MiraiConsoleLoggerController {
名称过长，考虑 `LoggerController`?

2020-10-25 12:30 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/MiraiConsoleLogger.kt
> +package net.mamoe.mirai.console.logging
internal package

2020-10-25 12:30 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/data/builtins/LoggerConfig.kt
> +    val defaultPriority by value(LogPriority.INFO)
add `@ValueDescription`

2020-10-25 12:32 UTC, Him188 requested changes
代码问题见文件内评论。

这样的控制看起来不错。有以下设计问题：

1. `getLoggerRegistration` 有什么作用？为什么要存储 registration？
2. `cacheLoggers` 有什么作用？为什么需要缓存 logger？

2020-10-25 12:53 UTC, Karlatemp commented
cache logger以支持通过identity得到相同logger，不过经过细想似乎没有这个必要，可保留以允许其他前端实现使用


get registration 为cache logger的实现的一部分

2020-10-25 12:57 UTC, Him188 commented
> cache logger以支持通过identity得到相同logger，不过经过细想似乎没有这个必要，可保留以允许其他前端实现使用 get registration 为cache logger的实现的一部分

我建议不保留，因为几乎没有需要保存 logger 的必要。

2020-10-25 16:31 UTC, Him188 requested changes
`LoggerControllerForFrontEnd` 不太好。
考虑在 terminal 前端实现 `LoggerConfig` 配置？（这样就可以只在后端提供 `LoggerCreator`，在前端实现）
后端可以提供原来的默认实现

2020-10-25 16:31 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/LoggerControllerPlatformBase.kt
> +public abstract class LoggerControllerPlatformBase : LoggerController {
此抽象类似乎没有必要

2020-10-26 04:38 UTC, Karlatemp commented
> 考虑在 terminal 前端实现 `LoggerConfig` 配置？（这样就可以只在后端提供 `LoggerCreator`，在前端实现）
> 后端可以提供原来的默认实现

在前端实现 `LoggerConfig` 意味着每个前端都需要自行实现此 config, 会降低代码复用性

2020-10-26 06:15 UTC, Him188 commented
> > 考虑在 terminal 前端实现 `LoggerConfig` 配置？（这样就可以只在后端提供 `LoggerCreator`，在前端实现）
> > 后端可以提供原来的默认实现
> 
> 在前端实现 `LoggerConfig` 意味着每个前端都需要自行实现此 config, 会降低代码复用性

没有问题, 因为它在后端不容易写

2020-10-28 05:46 UTC, Him188 requested changes

2020-10-28 05:46 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/data/AutoSavePluginData.kt
> +    public fun destroy() {
为什么要添加这个? PluginData 与 Logger 无关

2020-10-28 05:46 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/data/builtins/ConsoleDataScope.kt
> +    fun dropConfig(config: PluginConfig) {
不应该添加它

2020-10-28 05:46 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/internal/MiraiConsoleImplementationBridge.kt
> +        phase `setup logger controller`@{
不应该修改已经确认的 logger controller (前端提供)

2020-10-28 05:46 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/extensions/LoggerControllerProvider.kt
> +public interface LoggerControllerProvider : SingletonExtension<LoggerController> {
既然交给前端提供, 就不应该允许插件修改

Logger 绝大多数情况下不需要被插件控制

2020-10-28 22:58 UTC, Him188 commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/LogPriority.kt
> +    ALL(null),
似乎没有公开的 API 用到它？可以改成internal 吗

2020-10-30 10:22 UTC, Karlatemp commented on backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/logging/LogPriority.kt
> +    ALL(null),
该类除了内部使用外，还是提供给前端实现自定义 LoggerController 时使用的 util

2020-11-08 02:05 UTC, Him188 requested changes

2020-11-08 02:05 UTC, Him188 commented on backend/mirai-console/src/logging/LogPriority.kt
> +public enum class LogPriority {
`SimpleLogger.LogPriority` 已经足够, 这个类型没有必要

2020-11-08 02:05 UTC, Him188 commented on backend/mirai-console/src/logging/AbstractLoggerController.kt
> +public abstract class AbstractLoggerController : LoggerController {
从 `LoggerController` 继承 `@ConsoleExperimentalApi`

2020-11-08 02:07 UTC, Karlatemp commented on backend/mirai-console/src/logging/LogPriority.kt
> +public enum class LogPriority {
`SimpleLogger.LogPriority` 不足够， 没有 `NONE` 和 `ALL` 的表示方法

2020-11-08 02:09 UTC, Him188 commented on backend/mirai-console/src/logging/LogPriority.kt
> +public enum class LogPriority {
换一种思路, 为每个 priority 都添加配置? 一些时候需要 `DEBUG` 不需要 `VERBOSE` 而一些时候又需要 `VERBOSE` 不需要 `DEBUG`

2020-11-08 02:10 UTC, Him188 commented on backend/mirai-console/src/logging/LogPriority.kt
> +public enum class LogPriority {
我考虑的是这个 `LogPriority` 可能会与 mirai-core 的优先级产生迷惑性, 可能在 mirai-core 2.0 调整日志系统后再处理 mirai-console 的这个日志.

2020-11-08 02:21 UTC, Karlatemp commented on backend/mirai-console/src/logging/LogPriority.kt
> +public enum class LogPriority {
priority 都添加配置 其实并没有必要, 大多数日志系统都是这样设置一个level的

`LoggerController.shouldLog` 使用 `SimpleLogger.LogPriority` 是因为该 `shouldLog` 不应该有NONE和ALL这些等级, 就直接使用了 `SimpleLogger.LogPriority`, `LogPriority` 的优先级与 `SimpleLogger.LogPriority` 是对应的

2020-11-08 02:37 UTC, Him188 commented on backend/mirai-console/src/logging/LogPriority.kt
> +public enum class LogPriority {
那我觉得可以把 `LogPriority` 移动到 `LoggerController` 内

2020-11-08 02:40 UTC, Karlatemp commented on backend/mirai-console/src/logging/LogPriority.kt
> +public enum class LogPriority {
`LogPriority` 是在 `AbstractLoggerController` 才开始使用的, 所以移动到 `AbstractLoggerController` 里?

2020-11-08 03:28 UTC, Him188 approved these changes

2020-11-08 04:20 UTC, merged