Ansi support
mamoe/mirai-console pull request #219
Opened 2020-11-06 05:48 UTC by Karlatemp

2020-11-07 02:17 UTC, Him188 requested changes

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/MiraiConsole.kt
> +    public val isAnsiSupport: Boolean
`isAnsiSupported`

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +            noAnsi: Boolean = false,
`buildAnsiMessage` 不应检查 `noAnsi`

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +    public inline fun <R> builder(action: StringBuilder.() -> R): R = builder.action()
Why `builder`? 似乎不太合适

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public fun ansiMessageBuilder(
1. static
2. AnsiMessageBuilder 应该就是一个 builder，而不应该考虑 `noAnsi` 情况改变行为
3. 由于它是类似构造器的函数，可以是 `operator fun invoke` 并添加 `@JvmName` 调整名称

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +            size: Int = 16,
`size` 在此时可能被误解为 font size。请添加相关说明。

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +    public val builder: StringBuilder
此属性目的类似委托，应该叫做 `delegate`

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public inline fun buildAnsiMessage(
这个动作的主语应该是 `StringBuilder`。即改为类似 `StringBuilder.appendAnsi(lambda) = append(buildAnsiMessage(lambda))`

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public inline fun buildAnsiMessage(
这个方法可以放置 top-level

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public fun isAnsiSupport(sender: CommandSender): Boolean =
`is...Supported`

2020-11-07 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public suspend fun CommandSender.sendAnsiMessage(
可以 inline

2020-11-07 02:18 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public inline fun buildAnsiMessage(
类似 `buildString`，`buildMessageChain`

2020-11-07 02:21 UTC, Karlatemp commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +    public inline fun <R> builder(action: StringBuilder.() -> R): R = builder.action()
为了减少 `AnsiMessageBuilder` delegate代码量, 便直接允许访问, 或许函数名不是太合理

2020-11-07 02:23 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +    public inline fun <R> builder(action: StringBuilder.() -> R): R = builder.action()
似乎没有必要

2020-11-08 02:17 UTC, Him188 requested changes

2020-11-08 02:17 UTC, Him188 commented on backend/mirai-console/src/MiraiConsole.kt
> +    public val isAnsiSupported: Boolean
放在 `companion object` 之前会使得结构更清晰

2020-11-08 02:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public fun String.dropAnsi(): String = DROP_ANSI_PATTERN.replace(this, "")
添加文档

2020-11-28 04:43 UTC, Him188 requested changes

2020-11-28 04:43 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +    override fun append(c: Char): AnsiMessageBuilder {
` = apply { delegate.append(c) }` 就可以缩小到一行

2020-11-28 04:43 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public operator fun invoke(
调整名称

2020-11-28 12:17 UTC, Him188 requested changes

2020-11-28 12:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +     * 在 `noAnsi=true` 的时候会忽略此函数的调用
doc

2020-11-28 12:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public fun from(
doc，尤其是解释 noAnsi 参数作用

2020-11-28 12:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public fun from(
我更推荐 `create` 或者其他名称，`from` 似乎不太合适

2020-11-28 12:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +            noAnsi: Boolean = false
doc

2020-11-28 12:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public fun isAnsiSupported(sender: CommandSender): Boolean =
（提示）可能要改成成员函数，不过作为 experimental，可以先这样处理

2020-11-28 12:17 UTC, Him188 commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +public fun AnsiMessageBuilder(capacity: Int = 16): AnsiMessageBuilder = AnsiMessageBuilder(StringBuilder(capacity))
放在与类更近的位置

2020-11-28 12:30 UTC, Karlatemp commented on backend/mirai-console/src/util/AnsiMessageBuilder.kt
> +        public fun from(
此处为 从 `StringBuilder` 封装一个 `AnsiMessageBuilder`, `from` 可以在此情况使用

2020-11-28 13:36 UTC, Him188 approved these changes

2020-11-28 13:46 UTC, Him188 reviewed
`AnsiMessageBuilder.builder` 好, 还是 `AnsiMessageBuilder.create` 好?

2020-11-28 13:48 UTC, Karlatemp commented
应该 `create` 会更好, `AnsiMessageBuilder.builder` 会有歧义

2020-11-28 13:50 UTC, Him188 commented
> 应该 `create` 会更好, `AnsiMessageBuilder.builder` 会有歧义

fix 之后就可以 merge

2020-11-28 17:57 UTC, merged