Sandbox mode classes loading
mamoe/mirai-console pull request #338
Opened 2021-04-18 05:40 UTC by Karlatemp

#326

2021-04-18 05:55 UTC, Him188 commented
Tested?

2021-04-18 05:56 UTC, Karlatemp commented
No

2021-06-29 13:16 UTC, Him188 commented
有没有试过 coroutines 版本问题？
插件依赖 1.3 的协程，调用 (bot as CoroutineScope).coroutineContext 会不会因为 class 编译时间不同而异常？

更多的，假如实现的接口的成员有所变动呢

2021-07-03 06:17 UTC, Him188 requested changes

2021-07-03 06:17 UTC, Him188 commented on backend/mirai-console/build.gradle.kts
> +                    ksrc.associateWith(getByName("main"))
```suggestion
                    ksrc.associateWith(getByName("main"))
```

Kotlin stdlib 的 `associateWith`? 那它是 redundant 的

2021-07-03 06:17 UTC, Him188 commented on backend/mirai-console/build.gradle.kts
> +                plugins.walk().filter { it.isFile }.forEach { it.delete() }
```suggestion
                plugins.deleteRecursively()
```

2021-07-03 06:17 UTC, Him188 commented on backend/mirai-console/build.gradle.kts
> +                plugins.walk().filter { it.isFile }.forEach { it.delete() }
可能要 import

2021-07-03 06:19 UTC, Him188 commented
我觉得为测试插件各写一个 submodule 更好 (模拟真实环境用 buildPlugin 打包)

在测试时写 unit test, 启动不同的 Test 前端 with 指定 plugins 目录

2021-08-12 10:37 UTC, Him188 approved these changes

2021-08-12 11:10 UTC, Him188 requested changes
测试项目没有 include

2021-09-12 12:31 UTC, Him188 commented
any updates?

2021-09-12 14:46 UTC, Karlatemp commented
> any updates?

may no

2021-12-06 15:20 UTC, closed without merging