Support login account record
mamoe/mirai-console pull request #414
Opened 2021-10-07 07:22 UTC by Nambers

close #396

2021-10-30 13:09 UTC, Him188 requested changes

2021-10-30 13:09 UTC, Him188 commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +            pwd: String? = null,
这一名称会显示到 help 中, 应该保持

2021-10-30 13:09 UTC, Him188 commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +            val password:Any = pwd ?: let a@{
该 `let` 过于复杂, 应该抽一个 funciton

2021-10-30 13:09 UTC, Him188 commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    if(it == null){
`it` 仅允许在单行简单 `let` 中

2021-10-30 13:09 UTC, Him188 commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    (password is String) ->
多余的括号

2021-10-30 13:09 UTC, Him188 commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    (password is ByteArray) ->
多余的括号

2021-10-30 13:09 UTC, Him188 commented on backend/mirai-console/src/internal/data/builtins/AutoLoginConfig.kt
> +            autoLogin;
`AutoLoginConfig` 为什么要有 boolean 的 `autoLogin` 开关? 这个配置中的所有项应该都属于 autoLogin

2021-10-30 13:09 UTC, Him188 commented on backend/mirai-console/src/internal/data/builtins/AutoLoginConfig.kt
> +            autoLogin;
如果要做一个"是否启用自动登录"的开关, 可以考虑使用 `enabled` 等名称

2021-10-30 13:10 UTC, Him188 commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                        sendMessage("account record no found")
```suggestion
                        sendMessage("Could not find '$id' in AutoLogin config. Please specify password.")
```

2021-10-30 13:13 UTC, Him188 commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                        sendMessage("account record no found")
或者提示中文可能更好

2021-10-30 13:15 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                        }.doLogin()
将 bot setup 抽出到一个函数内

2021-10-30 13:15 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                        }.doLogin()
将 bot setup 抽出到一个函数内

2021-10-30 13:15 UTC, Karlatemp commented on backend/mirai-console/src/internal/MiraiConsoleImplementationBridge.kt
>                      val id = kotlin.runCatching {
bool, 使用 parseBoolean(可能要另外写) 而不是直接 ` == true`

2021-11-01 06:09 UTC, Nambers commented on backend/mirai-console/src/internal/MiraiConsoleImplementationBridge.kt
>                      val id = kotlin.runCatching {
这个的作用是什么? 就比如用.equal()?还是

2021-11-01 06:11 UTC, Nambers commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                        }.doLogin()
抽象是抽象到那种BotLogin(id:Long, pwd:Any, protocol):Bot 这样子吗
还是?

2021-11-01 09:10 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                        }.doLogin()
```kotlin
fun BotConfiguration.setup() {
}

MiraiConsole.addBot() {setup()}
```

2021-11-01 09:15 UTC, Karlatemp commented on backend/mirai-console/src/internal/MiraiConsoleImplementationBridge.kt
>                      val id = kotlin.runCatching {
处理一些其他情况(比如给了个数字, 字符串或者什么其他的

2021-11-01 11:17 UTC, Nambers commented on backend/mirai-console/src/internal/MiraiConsoleImplementationBridge.kt
>                      val id = kotlin.runCatching {
但是getOrDefault就根据default的值推断结果是bool类型了?
![image](https://user-images.githubusercontent.com/35139537/139663537-f3edea6d-8b74-44e5-832b-f0299a5dbeff.png)

2021-11-01 14:48 UTC, Karlatemp requested changes

2021-11-01 14:48 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +
放 `CommandSender.handle` 内

2021-11-01 14:48 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    else -> throw IllegalStateException()// Unreachable
```kotlin
                    pwd is String ->  MiraiConsole.addBot(id, pwd) {setup(protocol)  }.doLogin()
                    pwd is ByteArray ->  MiraiConsole.addBot(id, pwd) {     setup(protocol)  }.doLogin()
                    else -> throw AssertionError("Assertion failed, please report to https://github.com/mamoe/mirai-console/issues/new/choose, debug=${pwd.javaClass}")// Unreachable
```

2021-11-01 14:48 UTC, Karlatemp commented on backend/mirai-console/src/internal/data/builtins/AutoLoginConfig.kt
> +            enable;
保持原风格

```
protocol,
device,
enable,

;
```

2021-11-01 14:48 UTC, Karlatemp commented on settings.gradle.kts
>  @Suppress("ConstantConditionIf")
Should not included in pr

2021-11-08 09:11 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    return null
sender错误

2021-11-08 09:11 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +            val pwd: Any = password ?: (getPassword(id) ?: return)
多余的括号

2021-11-08 09:16 UTC, Nambers commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    return null
https://github.com/mamoe/mirai-console/pull/414/files/68429f2d292c528144240695d4af3c248592401a#diff-e3f77fd1fddf4ef8ae217265bf9aaaa5ba1dc93da191f8a1fd664023478df412R202
这里是否要去掉ScopeWith

2021-11-08 09:17 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    return null
no

2021-11-08 09:25 UTC, Nambers commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    return null
那我一起去掉吧

2021-11-08 09:25 UTC, Nambers commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +                    return null
ok

2021-11-08 10:04 UTC, Him188 approved these changes

2021-11-08 14:14 UTC, Karlatemp commented on backend/mirai-console/src/internal/MiraiConsoleImplementationBridge.kt
> +                }) {
有没有考虑过配置不是 `true / false` 的情况

2021-11-08 14:26 UTC, Nambers commented on backend/mirai-console/src/internal/MiraiConsoleImplementationBridge.kt
> +                }) {
```
it.configuration[ConfigurationKey.enable]?.toString()?.equals("true", true) ?: true
```
这样是否可行?

2021-11-08 14:55 UTC, Karlatemp approved these changes

2021-11-09 22:03 UTC, merged