Using PluginId as folder name
mamoe/mirai-console pull request #418
Opened 2021-11-05 00:53 UTC by Nambers

close #276

2021-11-09 21:55 UTC, Him188 reviewed
实现应该是要么一直必须使用 id, 要么必须使用 name. PR 的无法自动迁移就使用旧 name 的方案会让数据产生不确定性.

在迁移成功时也应该再加一个 logging 告知用户. 在迁移失败时应该告知用户并以某种方式禁用该插件或*直接关闭服务器* (仅当该迁移过程在服务器启动过程中允许)

综上, 我建议在获取到 Plugin 实例后, 就尽可能地执行迁移, 在任一插件可能迁移失败时直接关闭服务器并提示解决方案. 这样虽然有可能导致小概率的误操作 (用户放了一个与插件名相同的目录而该插件并不使用 dataFolder, 那么该目录也会被重命名)

2021-11-09 21:55 UTC, Him188 commented on backend/mirai-console/src/internal/plugin/JvmPluginInternal.kt
> +                    return@lazy PluginManager.pluginsDataPath.resolve(description.name)
这很容易产生不确定情况

2021-11-10 06:24 UTC, Nambers commented
@Him188 这样子吗，需不需要直接写在onEnable()里而不是现在的lazy里
目前就cancel后还要等onEnable()执行完才close console

2021-11-17 12:57 UTC, Him188 commented
应该要写在 PluginManager 在获取到所有插件 Plugin 实例后进行

2021-11-18 00:24 UTC, Nambers commented
> 应该要写在 PluginManager 在获取到所有插件 Plugin 实例后进行

在 `JvmPluginLoaderImpl` 的 `load` 里面写会不会更好
因为 `PluginManager` 里面都是 `Plugin` 类型，设计上看起来是不管内部，而 `dataFolder` 是在 `JvmPlugin` 里有

2021-11-18 00:48 UTC, Him188 commented
@Nambers Indeed.

2021-11-26 18:25 UTC, Him188 requested changes

2021-11-26 18:25 UTC, Him188 commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +                    })被占用, mcl将自动关闭请于下次启动前删除该文件夹"
```suggestion
                    })被占用, Mirai Console 将自动关闭, 请删除或移动该目录后再启动"
```

2021-11-26 18:25 UTC, Him188 commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +                    "配置文件夹(${
```suggestion
                    "配置目录(${
```

2021-11-26 18:25 UTC, Him188 commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +                PluginManager.pluginsDataPath.resolve(plugin.description.name).toFile().renameTo(
此操作必须告知用户

2021-11-26 18:25 UTC, Him188 commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +                logger.error(it)
不要只打印错误, 还需要告诉该错误来自哪里

2021-11-26 18:25 UTC, Him188 commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +        if (PluginManager.pluginsDataPath.resolve(plugin.description.name).toFile().exists()) {
避免代码重复 `PluginManager.pluginsDataPath.resolve(plugin.description.name).toFile()`

2021-11-28 14:47 UTC, Him188 requested changes

2021-11-28 14:47 UTC, Him188 commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +                logger.error("移动配置目录失败, Mirai Console 将自动关闭\n$it")
```suggestion
                logger.error("移动配置目录失败, Mirai Console 将自动关闭\n", it)
```

2021-11-28 14:51 UTC, Karlatemp requested changes
1. Tested?
2. 消息过于密集，适当添加换行 (使用两次 logger)
3. (仅建议) 可以考虑输出的路径为相对于 console 运行目录的路径 (caused by 2.)

2021-11-28 14:51 UTC, Karlatemp commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +                nameFolder.renameTo(idFolder)
```java
    /**
     * Renames the file denoted by this abstract pathname.
     *
     * ....
     * @return  {@code true} if and only if the renaming succeeded;
     *          {@code false} otherwise
     *
     * @throws  ....
     */
    public boolean renameTo(File dest) { /**/ }
```

`@see` https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/io/File.java#L1421-L1464

2021-11-28 14:51 UTC, Karlatemp commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +                logger.info("移动 ${plugin.description.name} 的配置目录(${nameFolder.absolutePath})到 ${idFolder.absolutePath}")
`plugin.smartToString()` (或者可能是 `plugin.description.smartToString()`)

2021-11-28 14:51 UTC, Karlatemp commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +                    "配置目录(${idFolder.absolutePath})被占用, Mirai Console 将自动关闭, 请删除或移动该目录后再启动"
没有显示正在移动哪个插件的目录，没有显示从什么移动到什么目录

2021-11-28 14:51 UTC, Karlatemp commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +            if (idFolder.exists()) {
```kotlin
if (idFolder.exists() && idFolder.listFiles()?.size != 0)
```

2021-11-29 01:41 UTC, Nambers commented
> 1. Tested?
> 2. 消息过于密集，适当添加换行 (使用两次 logger)
> 3. (仅建议) 可以考虑输出的路径为相对于 console 运行目录的路径 (caused by 2.)

如果目标文件夹下没有任何文件(`listFiles().size == 0`)，使用rename会返回false不抛出任何异常
这样的话是要删除目标文件夹然后移动，还是发出log让用户手动移动?

2021-11-29 01:46 UTC, Him188 commented
建议添加单元测试, 见 CommandTest 查看如何在 test 启动 console

2021-11-29 02:18 UTC, Nambers commented
> 建议添加单元测试, 见 CommandTest 查看如何在 test 启动 console

差点忘了name == id的情况了, 为什么这个test每个单个执行就可以pass, 但是我整个类一起执行就会报错 `kotlinx.coroutines.JobCancellationException: Job was cancelled;`
是文件夹里面没清理吗

2021-11-29 03:31 UTC, Him188 commented
因为 test 框架可能有 bug

2021-11-29 07:29 UTC, Nambers commented
> 因为 test 框架可能有 bug

对协程的这方面不是很熟悉，目前没找到什么方法解决这个问题，在本地这个test是可以pass的
你们看看怎么写?
看Coroutine context是supervisor job 应该没什么问题可能

2021-11-29 09:23 UTC, Karlatemp reviewed
需要当目标目录为空的时候也能移动成功，但是逻辑并没有处理目标目录存在切为空的情况

2021-11-29 14:14 UTC, Karlatemp approved these changes
*Logic review ok*

2021-11-30 20:29 UTC, Him188 commented on backend/mirai-console/src/internal/plugin/BuiltInJvmPluginLoaderImpl.kt
> +            }.onFailure {
缺少移动成功时的提示

2021-11-30 20:29 UTC, Him188 commented on backend/mirai-console/test/data/PluginMovingTests.kt
> +    }
应该拆分成四个 fun

2021-11-30 20:29 UTC, Him188 commented on backend/mirai-console/test/AbstractConsoleTest.kt
> +    var exceptCancel = true
expectCancel?
```suggestion
    var cancelOnFinish = true
```

2021-11-30 23:49 UTC, Nambers commented on backend/mirai-console/test/data/PluginMovingTests.kt
> +    }
之前拆成4个@test fun的时候本地和CI运行整个类就会报错, 那个`kotlinx.coroutines.JobCancellationException: Job was cancelled;`
合并成一个的时候本地运行不会报错，但是CI一样会报错

2021-12-01 01:15 UTC, Him188 commented on backend/mirai-console/test/data/PluginMovingTests.kt
> +    }
ok，那还是等以后改了测试框架再改

2021-12-01 01:22 UTC, Nambers commented on backend/mirai-console/test/data/PluginMovingTests.kt
> +    }
> 

看起来像是MiraiConsoleImpl的问题，要让::instance.isInitialized 返回false, 也就是说抹除里面的lateinit instance的赋值

2021-12-01 01:50 UTC, Nambers commented
尝试修了下，没找到解决方法 :(
大概要注意的地方有
- 测试里plugin.load里的cancel方法会报错，可能要提出一个cancel方法在MiraiConsole，然后在testMiraiConsole里重载
- MiraiConsoleImpl.instance.start里的isInitial, 可能需要传入一个testOnly的参数来在test里代替这个, 因为test里每个其实相当于重新开个MiraiConsole, 该属性应该是false
- `@afterEach`的cancel会报错, 这个应该是就用目前这个`cancelOnFinish`控制

2021-12-01 02:46 UTC, Him188 approved these changes

2021-12-01 17:59 UTC, Him188 commented
试试 rebase 到 master 然后换用新的 AbstractConsoleTest.kt?

2021-12-03 19:37 UTC, merged

2021-12-03 19:38 UTC, Him188 commented
看了一下, 问题是现在 Console 的很多服务都是静态的, 没法重启, 得等 https://github.com/Him188/kotlin-dynamic-delegation