loadPluginCommand
mamoe/mirai-console pull request #421
Opened 2021-11-17 12:09 UTC by Nambers

close #358
没找到加载插件的方法，就自己从 `BuiltInJvmPluginLoaderImpl` 的 `extractPlugins()` 糊了一个
测试了一下确实可以用

2021-11-17 12:46 UTC, Him188 commented
设计上是不允许热加载插件的

2021-11-17 12:50 UTC, Nambers commented
> 设计上是不允许热加载插件的

我觉得也不怎么算热加载吧，只是增加新类，没 更新 什么地方，把监听器注册进去就好了
不过我也没看过那方面代码，如果确实存在不可预测问题就关了这个pr吧
我是看前面那个issue里你觉得没什么问题就顺手写了

2021-11-17 14:13 UTC, Karlatemp commented
添加新配置，默认值 false，以告知user确认她自己在干什么的时候才允许动态加载等危险操作

2021-11-17 14:16 UTC, Karlatemp commented
并且限制该类命令必须只能由控制台执行，并且警告信息需要为红色或浅红色这种警告类颜色

2021-11-17 23:55 UTC, Nambers commented
> 添加新配置，默认值 false，以告知user确认她自己在干什么的时候才允许动态加载等危险操作

在配置文件里加一个 `Advanced_operation` 的项, 然后在console启动的时候如果这个true的话，弹出 `进阶操作已经启用, 使用进阶操作可能会导致不可预测的问题, 是否确认打开?(Y/N)` 这种?

2021-11-18 14:27 UTC, Karlatemp requested changes

2021-11-18 14:27 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +        }
避免 ctrl+cv

2021-11-18 14:27 UTC, Karlatemp commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +            val f = File(path)
`MiraiConsole.???path.resolve`, 反正不可以直接使用当前目录

2021-11-30 01:46 UTC, Nambers commented on backend/mirai-console/src/command/BuiltInCommands.kt
> +            val f = File(path)
> `MiraiConsole.???path.resolve`, 反正不可以直接使用当前目录

是限制插件只能在plugins/ 下吗?

2021-12-06 15:20 UTC, closed without merging

2021-12-08 02:16 UTC, Nambers commented
@Karlatemp 这个还有必要实现吗(
如果还有必要的话我在mirai再开一个

2021-12-08 10:11 UTC, Him188 commented
我觉得目前不用